### ISSUE TITLE
Can't npm install the package on my local

### ISSUE THREAD

**Issue by SystemDZ** [ptkdev-boilerplate/svelte-kit-ssr-boilerplate#2]
![image](https://user-images.githubusercontent.com/5507558/114563228-3d480400-9c3d-11eb-9395-1884b748d3da.png)

**Comment by ptkdev** [comment]
@SystemDZ Read first line, you need update your nodejs to `>= v14` and npm from `v6` to `v7` with `npm install npm@latest -g`

**Comment by SystemDZ** [comment]
That solved the problem thanks
I think documentation should have a section clear with red color or somehow to bring attention for must-do steps.

**Comment by ptkdev** [comment]
This is a npm issue, i added required node version to [package.json](https://github.com/ptkdev-boilerplate/svelte-kit-ssr-boilerplate/blob/018907ae6b702490686551fa0c71536c152fe26d/package.json#L25). NPM warned you about the incompatible package-lock
